package futbolxd.Ventanas;

import futbolxd.clases.ArchivoPlano;
import futbolxd.clases.Equipo;
import java.awt.Image;
import java.util.ArrayList;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author km121
 */
public class AgregarEquipo extends javax.swing.JFrame {

    ArchivoPlano archivo = new ArchivoPlano();
    Equipo equipo = new Equipo();
    
   



    /**
     * Creates new form AgregarEquipo
     */
    public AgregarEquipo() {
        initComponents();

        // llamar la imagen del archivo, (ruta imagen y el label)
        SetImageLabel(FondoAgregarEquipo, "src/futbolxd/Imagenes/Fondo_nose.jpg");
        this.setLocationRelativeTo(this);

    }

    // funcion para ajustar el tamaño de la imagen que se llama por medio de la ruta
    public void SetImageLabel(JLabel labelname, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        panelInfor = new javax.swing.JPanel();
        txtNombreEquipo = new javax.swing.JLabel();
        varNombreEntrenador = new javax.swing.JTextField();
        txtNombreEquipo2 = new javax.swing.JLabel();
        varNombreEquipo = new javax.swing.JTextField();
        BotonGuardar = new javax.swing.JButton();
        BotonAtrasX = new javax.swing.JButton();
        PaneltxtRegis = new javax.swing.JPanel();
        txtRegistroDelEquipo = new javax.swing.JLabel();
        FondoAgregarEquipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInfor.setBackground(new java.awt.Color(255, 255, 255));
        panelInfor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombreEquipo.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEquipo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        txtNombreEquipo.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreEquipo.setText("Nombre Equipo");

        varNombreEntrenador.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        varNombreEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNombreEntrenadorActionPerformed(evt);
            }
        });

        txtNombreEquipo2.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEquipo2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        txtNombreEquipo2.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreEquipo2.setText("Nombre Entrenador");

        varNombreEquipo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        varNombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNombreEquipoActionPerformed(evt);
            }
        });

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonAtrasX.setBackground(new java.awt.Color(0, 0, 0));
        BotonAtrasX.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        BotonAtrasX.setForeground(new java.awt.Color(255, 255, 255));
        BotonAtrasX.setText("X");
        BotonAtrasX.setBorder(null);
        BotonAtrasX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInforLayout = new javax.swing.GroupLayout(panelInfor);
        panelInfor.setLayout(panelInforLayout);
        panelInforLayout.setHorizontalGroup(
            panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInforLayout.createSequentialGroup()
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInforLayout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(varNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(varNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelInforLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(BotonGuardar))
                            .addGroup(panelInforLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInforLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(txtNombreEquipo2)))
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInforLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonAtrasX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelInforLayout.setVerticalGroup(
            panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInforLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonAtrasX, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txtNombreEquipo)
                .addGap(18, 18, 18)
                .addComponent(varNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(txtNombreEquipo2)
                .addGap(18, 18, 18)
                .addComponent(varNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BotonGuardar)
                .addGap(32, 32, 32))
        );

        PanelFondo.add(panelInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 450, 340));

        PaneltxtRegis.setBackground(new java.awt.Color(255, 255, 255));
        PaneltxtRegis.setForeground(new java.awt.Color(249, 249, 249));

        txtRegistroDelEquipo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        txtRegistroDelEquipo.setForeground(new java.awt.Color(0, 0, 0));
        txtRegistroDelEquipo.setText("REGISTRO DEL EQUIPO");

        javax.swing.GroupLayout PaneltxtRegisLayout = new javax.swing.GroupLayout(PaneltxtRegis);
        PaneltxtRegis.setLayout(PaneltxtRegisLayout);
        PaneltxtRegisLayout.setHorizontalGroup(
            PaneltxtRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(PaneltxtRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PaneltxtRegisLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtRegistroDelEquipo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PaneltxtRegisLayout.setVerticalGroup(
            PaneltxtRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(PaneltxtRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PaneltxtRegisLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtRegistroDelEquipo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelFondo.add(PaneltxtRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 270, 80));
        PanelFondo.add(FondoAgregarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varNombreEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNombreEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNombreEntrenadorActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        if (varNombreEntrenador.getText().isEmpty() || varNombreEquipo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos!");
        } else {

            // se llama la clase de equipos
            AgregarEquipo hola = new AgregarEquipo();

            equipo.setNombreEquipo(varNombreEquipo.getText());
            equipo.setNombreEntrenador(varNombreEntrenador.getText());
            String Nombre = equipo.getNombreEquipo();
            boolean uwu = archivo.agregarEquipo(Nombre);
            System.out.println(""+uwu);
           
            
            // tener un numero al azar
            int min = 1000;
            int max = 5000;
            equipo.setNumeroRandom(hola.getNumeroRandom(min, max));
            
            
            //mandar los datos al archivo
            String fila = equipo.getNumeroRandom() + ";" + equipo.getNombreEquipo() + ";" + equipo.getNombreEntrenador() + "\n";

            //le mandamos a la clase archivo la fila
            archivo.escribir(fila);

            // para saber como esta el archivo
            System.out.print(fila);

            // vacia los jtextfield
            varNombreEquipo.setText("");
            varNombreEntrenador.setText("");

            // muestra el mensaje y el codigo del equipo
            JOptionPane.showMessageDialog(null, """
                                                Equipo Registrado Correctamente
                                                Codigo del equipo: 
                                                """ + equipo.getNumeroRandom());
        
              
            
        }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    // metodo para crear un numero al azar
    private int getNumeroRandom(int min, int max) {
        return ThreadLocalRandom.current().nextInt(min, max);
    }

    private void varNombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNombreEquipoActionPerformed

    }//GEN-LAST:event_varNombreEquipoActionPerformed

    private void BotonAtrasXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasXActionPerformed
        // abre la ventana de menuUsuario
        MenuUsuario atrasframe = new MenuUsuario();
        atrasframe.setVisible(true);
        // cierra esta ventana
        this.dispose();
    }//GEN-LAST:event_BotonAtrasXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtrasX;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JLabel FondoAgregarEquipo;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PaneltxtRegis;
    private javax.swing.JPanel panelInfor;
    private javax.swing.JLabel txtNombreEquipo;
    private javax.swing.JLabel txtNombreEquipo2;
    private javax.swing.JLabel txtRegistroDelEquipo;
    private javax.swing.JTextField varNombreEntrenador;
    private javax.swing.JTextField varNombreEquipo;
    // End of variables declaration//GEN-END:variables
}
