package Futbolxd.Ventanas;

import futbolxd.Ventanas.EntrarUsuario;
import futbolxd.Ventanas.InvitadoUsuario;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class Inicio extends javax.swing.JFrame {


    public Inicio() {
        initComponents();
        
        // llamar la imagen del archivo, (ruta imagen y el label)
        SetImageLabel(FondoInicio, "src/futbolxd/imagenes/Fondo_Inicio.jpg");
        SetImageLabel(FondoIcono,"src/futbolxd/imagenes/Icono.png");
        SetImageLabel(FondoLogo,"src/futbolxd/imagenes/logo.png");
        this.setLocationRelativeTo(this);
    }

    // funcion para ajustar el tamaño de la imagen que se llama por medio de la ruta
    public void SetImageLabel(JLabel labelname, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        Panel_obsiones = new javax.swing.JPanel();
        FondoIcono = new javax.swing.JLabel();
        BotonEntrarInicio = new javax.swing.JButton();
        TextoBienvenidos = new javax.swing.JLabel();
        BotonINVITADOSinicio = new javax.swing.JButton();
        FondoLogo = new javax.swing.JLabel();
        FondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_obsiones.setBackground(new java.awt.Color(255, 255, 255));

        BotonEntrarInicio.setBackground(new java.awt.Color(58, 107, 113));
        BotonEntrarInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonEntrarInicio.setForeground(new java.awt.Color(255, 255, 255));
        BotonEntrarInicio.setText("ENTRAR");
        BotonEntrarInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEntrarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntrarInicioActionPerformed(evt);
            }
        });

        TextoBienvenidos.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        TextoBienvenidos.setForeground(new java.awt.Color(0, 0, 0));
        TextoBienvenidos.setText("Bienvenidos");

        BotonINVITADOSinicio.setBackground(new java.awt.Color(14, 33, 40));
        BotonINVITADOSinicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonINVITADOSinicio.setForeground(new java.awt.Color(255, 255, 255));
        BotonINVITADOSinicio.setText("INVITADO");
        BotonINVITADOSinicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonINVITADOSinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonINVITADOSinicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_obsionesLayout = new javax.swing.GroupLayout(Panel_obsiones);
        Panel_obsiones.setLayout(Panel_obsionesLayout);
        Panel_obsionesLayout.setHorizontalGroup(
            Panel_obsionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_obsionesLayout.createSequentialGroup()
                .addComponent(FondoIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(TextoBienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BotonEntrarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(BotonINVITADOSinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        Panel_obsionesLayout.setVerticalGroup(
            Panel_obsionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_obsionesLayout.createSequentialGroup()
                .addComponent(FondoIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Panel_obsionesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Panel_obsionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoBienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEntrarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonINVITADOSinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelFondo.add(Panel_obsiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 90));

        FondoLogo.setBackground(new java.awt.Color(255, 255, 255));
        PanelFondo.add(FondoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 310, 280));

        FondoInicio.setForeground(new java.awt.Color(255, 255, 255));
        PanelFondo.add(FondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEntrarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntrarInicioActionPerformed
        // llamar la ventada de EntrarUsuario
        EntrarUsuario entrarframe = new EntrarUsuario();
        entrarframe.setVisible(true);
        
        // elimina la ventada anterior
        this.dispose();
    }//GEN-LAST:event_BotonEntrarInicioActionPerformed

    private void BotonINVITADOSinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonINVITADOSinicioActionPerformed
        // llamar la ventada de InvitadoUsuario
        InvitadoUsuario invitadoframe = new InvitadoUsuario();
        invitadoframe.setVisible(true);
        
        // elimina la ventada anterior
        this.dispose();
    }//GEN-LAST:event_BotonINVITADOSinicioActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrarInicio;
    private javax.swing.JButton BotonINVITADOSinicio;
    private javax.swing.JLabel FondoIcono;
    private javax.swing.JLabel FondoInicio;
    private javax.swing.JLabel FondoLogo;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel Panel_obsiones;
    private javax.swing.JLabel TextoBienvenidos;
    // End of variables declaration//GEN-END:variables
}
